spring.application.name=economy-dict

spring.datasource.url=jdbc:postgresql://localhost:9001/economy_dict
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=CHANGE_ME_JWT_SECRET
app.jwt.expiration-ms=86400000

openai.api.base-url=https://api.openai.com
openai.api.key=CHANGE_ME_OPENAI_KEY
openai.api.model=gpt-4o-mini

server.port=8081
